# Generated by Django 5.0.7 on 2024-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
