# Generated by Django 5.0.6 on 2024-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0004_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
